apiVersion: v1
kind: ConfigMap
metadata:
  name: eduplat-backend-config
  namespace: eduplat
data:
  NODE_ENV: "production"
  PORT: "4000"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  FILE_STORAGE_DRIVER: "s3"
  S3_REGION: "us-east-1"
  S3_SIGNED_URL_TTL: "900"
  AI_DEFAULT_PROVIDER: "openai"
  OPENAI_BASE_URL: "https://api.openai.com/v1"
  DEEPSEEK_BASE_URL: "https://api.deepseek.com"
  HUGGINGFACE_BASE_URL: "https://api-inference.huggingface.co"
