apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eduplat-backend
  namespace: eduplat
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.eduplat.example
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: eduplat-backend
                port:
                  number: 80
