apiVersion: v1
kind: Service
metadata:
  name: eduplat-backend
  namespace: eduplat
spec:
  selector:
    app: eduplat-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
